#!/bin/bash

echo "🚀 Simple MotoRev Deployment"
echo "============================"
echo ""

echo "✅ Your Railway account is set up with Pro access!"
echo ""
echo "🌐 To deploy your backend:"
echo ""
echo "1. Go to the Railway dashboard (should be open in your browser)"
echo "2. Click 'New Project'"
echo "3. Select 'Deploy from GitHub repo'"
echo "4. Choose your MotoRev repository"
echo "5. Railway will auto-detect it's a Node.js app"
echo "6. Add MySQL database: Click 'New' → 'Database' → 'MySQL'"
echo "7. Set environment variables:"
echo "   - NODE_ENV=production"
echo "   - JWT_SECRET=your-secret-key-here"
echo "   - CORS_ORIGIN=*"
echo ""
echo "8. Railway will automatically deploy your app!"
echo ""
echo "🎉 After deployment, you'll get a URL like:"
echo "   https://motorev-backend-production.up.railway.app"
echo ""
echo "📱 Your iOS app is already configured to use this URL for production!"
echo ""
echo "✅ Any user with your app can now connect to your server!"
echo ""
echo "🔧 Need help? The Railway dashboard has everything you need!" 