[build]
builder = "nixpacks"
buildCommand = "cd MotoRevBackend && npm install"

[deploy]
startCommand = "cd MotoRevBackend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
